clear
syms theta1 A theta2 B theta3 C theta4 D theta5 E theta6 F

vals=[theta1, A , 0 , 0;...
      theta2, 0 , 0 , B;...
      theta3, 0 , 0 , C;...
      theta4, 0 , 0 , D;...
      theta5, 0 , 0 , E;...
      theta6, 0 , 0 , F]

for n = 1:6
    
    t = vals(n,1);
    rz= t;
    tz= vals(n,2);
    rx= vals(n,3);
    tx= vals(n,4);
    
    linkvar = [rz,tz,rx,tx];
        
    if (n==1)
        transMat1= [cosd(rz), -sind(rz)*cosd(tx), sind(rz)*sind(rx), tx*(cosd(rz));...
            sind(rz), cosd(rz)*cosd(rx), -cosd(rz)*sind(rx), tx*(sind(rz));...
            0,sind(rx),cosd(rz),tz;...
            0,0,0,1]
    end
    if (n==2)
        transMat2= [cosd(rz), -sind(rz)*cosd(tx), sind(rz)*sind(rx), tx*(cosd(rz));...
            sind(rz), cosd(rz)*cosd(rx), -cosd(rz)*sind(rx), tx*(sind(rz));...
            0,sind(rx),cosd(rz),tz;...
            0,0,0,1]
    end
    if (n==3)
        transMat3= [cosd(rz), -sind(rz)*cosd(tx), sind(rz)*sind(rx), tx*(cosd(rz));...
            sind(rz), cosd(rz)*cosd(rx), -cosd(rz)*sind(rx), tx*(sind(rz));...
            0,sind(rx),cosd(rz),tz;...
            0,0,0,1]
    end
    if (n==4)
        transMat4= [cosd(rz), -sind(rz)*cosd(tx), sind(rz)*sind(rx), tx*(cosd(rz));...
            sind(rz), cosd(rz)*cosd(rx), -cosd(rz)*sind(rx), tx*(sind(rz));...
            0,sind(rx),cosd(rz),tz;...
            0,0,0,1]
    end
    if (n==5)
        transMat5= [cosd(rz), -sind(rz)*cosd(tx), sind(rz)*sind(rx), tx*(cosd(rz));...
            sind(rz), cosd(rz)*cosd(rx), -cosd(rz)*sind(rx), tx*(sind(rz));...
            0,sind(rx),cosd(rz),tz;...
            0,0,0,1]
    end
    if (n==6)
        transMat6= [cosd(rz), -sind(rz)*cosd(tx), sind(rz)*sind(rx), tx*(cosd(rz));...
            sind(rz), cosd(rz)*cosd(rx), -cosd(rz)*sind(rx), tx*(sind(rz));...
            0,sind(rx),cosd(rz),tz;...
            0,0,0,1]
    end
    
end

tip = transMat1*transMat2*transMat3*transMat4*transMat5*transMat6