clear
syms theta1Z AZ theta2Z BZ theta3Z CZ theta4Z DZ theta5Z EZ theta6Z FZ...
     theta1X AX theta2X BX theta3X CX theta4X DX theta5X EX theta6X FX

%symbolic transltation and Rotation along Z and X

vals=[theta1Z, AZ , theta1X , AX;...
      theta2Z, BZ , theta2X , BX;...
      theta3Z, CZ , theta3X , CX;...
      theta4Z, DZ , theta4X , DX;...
      theta5Z, EZ , theta5X , EX;...
      theta6Z, FZ , theta6X , FX]

for n = 1:6
    
    t = vals(n,1);
    rz= t;
    tz= vals(n,2);
    rx= vals(n,3);
    tx= vals(n,4);
    
    linkvar = [rz,tz,rx,tx];
        
    if (n==1)
        transMat1= [cosd(rz), -sind(rz)*cosd(tx), sind(rz)*sind(rx), tx*(cosd(rz));...
            sind(rz), cosd(rz)*cosd(rx), -cosd(rz)*sind(rx), tx*(sind(rz));...
            0,sind(rx),cosd(rz),tz;...
            0,0,0,1]
    end
    if (n==2)
        transMat2= [cosd(rz), -sind(rz)*cosd(tx), sind(rz)*sind(rx), tx*(cosd(rz));...
            sind(rz), cosd(rz)*cosd(rx), -cosd(rz)*sind(rx), tx*(sind(rz));...
            0,sind(rx),cosd(rz),tz;...
            0,0,0,1]
    end
    if (n==3)
        transMat3= [cosd(rz), -sind(rz)*cosd(tx), sind(rz)*sind(rx), tx*(cosd(rz));...
            sind(rz), cosd(rz)*cosd(rx), -cosd(rz)*sind(rx), tx*(sind(rz));...
            0,sind(rx),cosd(rz),tz;...
            0,0,0,1]
    end
    if (n==4)
        transMat4= [cosd(rz), -sind(rz)*cosd(tx), sind(rz)*sind(rx), tx*(cosd(rz));...
            sind(rz), cosd(rz)*cosd(rx), -cosd(rz)*sind(rx), tx*(sind(rz));...
            0,sind(rx),cosd(rz),tz;...
            0,0,0,1]
    end
    if (n==5)
        transMat5= [cosd(rz), -sind(rz)*cosd(tx), sind(rz)*sind(rx), tx*(cosd(rz));...
            sind(rz), cosd(rz)*cosd(rx), -cosd(rz)*sind(rx), tx*(sind(rz));...
            0,sind(rx),cosd(rz),tz;...
            0,0,0,1]
    end
    if (n==6)
        transMat6= [cosd(rz), -sind(rz)*cosd(tx), sind(rz)*sind(rx), tx*(cosd(rz));...
            sind(rz), cosd(rz)*cosd(rx), -cosd(rz)*sind(rx), tx*(sind(rz));...
            0,sind(rx),cosd(rz),tz;...
            0,0,0,1]
    end
    
end

tip = transMat1*transMat2*transMat3*transMat4*transMat5*transMat6